# Generated by Django 3.1.6 on 2021-02-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fieldName',
            new_name='subtitle',
        ),
    ]
