# Generated by Django 3.1.6 on 2021-02-02 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210202_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myApp.category'),
            preserve_default=False,
        ),
    ]
