# Generated by Django 3.1.6 on 2021-02-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_post_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorie',
        ),
    ]
